"""
Atlas RRT for Motion Planning on Constraint Manifold
Reference:
    https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=6352929
    https://journals.sagepub.com/doi/pdf/10.1177/0278364919868530
"""

import time
import torch
from torch.autograd.functional import jacobian

class Chart:
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    tol = 1e-6                                          # Accuracy for calculating Φ
    max_iteration = 500                                 # Time limit for exponential map
    eps = 1e-4                                          # Accuracy for exponential map

    epsilon = 5e-2                                      # Chart validity error
    alpha = torch.tensor(torch.pi / 3, device = device) # Chart validaty curvature
    rho = 1e-1                                          # Chart validaty spam
    beta = 2.0                                          # Exploration speed

    rho_s = rho * beta                                  # Sample Range

    """
    A single chart in an atlas

    Parameters:
    ----------
    xc: n-dimension torch.tensor
        The center point of the chart in ambient space
    F: function
        The implicit constraint function
    index: int
        A number as the identifier for this chart in the atlas
    """
    def __init__(self, xc: torch.tensor, F, index):
        self.xc = xc
        self.F = F
        if not F(xc).size()[0] == 0:
            self.J = jacobian(F, xc)                        # Should be full rank
            if self.J.ndim == 1:
                self.J = self.J.unsqueeze(0)
            self.n = self.J.size()[1]
            self.k = self.J.size()[1] - self.J.size()[0]

            _, _, Vh = torch.linalg.svd(self.J)
            self.Phi = Vh.T[:, self.n - self.k:]            # Orthogonal Basis
        else:                                               # If there is no constraint
            self.n = xc.size()[0]
            self.k = self.n
            self.J = torch.zeros((0, self.n), dtype=xc.dtype, device=xc.device)
            self.Phi = torch.eye(self.n, dtype = xc.dtype, device = xc.device)

        self.index = index

        """
        NOTE: L[i] inequality is generated by neighbors[i]
        """
        self.L = []                                     # All linear inequalities
        self.neighbors = []                             # All neighbor charts in atlas
        self.nodes = []                                 # All nodes registered in chart

    """
    Map φ from tangent space to configuration space
    """
    def phi(self, u: torch.tensor):
        return self.xc + self.Phi @ u
    
    """
    Exponential map ᴪ maps tangent space points to the manifold
    """
    def psi(self, u: torch.tensor):
        x_init = self.phi(u)                            # Initialize using approximation
        x = x_init.clone()
        for _ in range(Chart.max_iteration):
            b1 = self.F(x)
            b1 = b1.view(-1) if b1.ndim == 0 else b1
            b2 = self.Phi.T @ (x - x_init)
            b = torch.cat([b1, b2], dim = 0)
            if torch.norm(b, p=2) <= Chart.eps:
                break
            A = torch.vstack([self.J, self.Phi.T])
            x = x - A.inverse() @ b
        else:
            raise RuntimeError("Exponential Map Time Out")
        return x
    
    """
    Logarithmic map ᴪ^(-1) act as projecting point to tangent space
    """
    def psi_inv(self, x: torch.tensor):
        return self.Phi.T @ (x - self.xc)
    
    """
    Whether a point is in the validity area of the chart
    """
    def in_V(self, u: torch.tensor, x: torch.tensor = None, curvature_index = None):
        if torch.norm(u, 2) >= Chart.rho:
            return False
        
        if x is None:
            x = self.psi(u)
        if torch.norm(x - self.phi(u), 2) >= Chart.epsilon:
            return False
        
        if curvature_index is None:
            if self.k < self.n:                         # If there is constraint
                Jx = jacobian(self.F, x)
                _, _, Vh = torch.linalg.svd(Jx)
                Phi_x = Vh.T[:, self.n - self.k:]
                curvature_index = torch.linalg.matrix_norm(self.Phi.T @ Phi_x, ord=2)
            else:                                       # If there is no constraint
                curvature_index = 1.0
        if curvature_index < torch.cos(Chart.alpha):
            return False

        return True
    
    """
    Whether a point is in the polyedral of the chart
    """
    def in_P(self, u: torch.tensor):
        for l in self.L:
            if torch.dot(u, l[0]) >= l[1]:
                return False
        return True
    
    """
    Find the most suitable neighbor for a out-of-P point
    """
    def find_best_neighbor(self, u, x):
        possible_neighbors = []
        for i in range(len(self.L)):
            l = self.L[i]
            if torch.dot(u, l[0]) >= l[1]:
                possible_neighbors.append(self.neighbors[i])
        best_chart = None
        min_error = Chart.epsilon
        for neighbor_chart in possible_neighbors:
            un = neighbor_chart.psi_inv(x)
            error = torch.norm(neighbor_chart.phi(un) - x, p = 2)
            if error < min_error:
                min_error = error
                best_chart = neighbor_chart
        if best_chart is None:
            raise RuntimeError("Could not find appropriate neighbor chart!")
        return best_chart

    """
    Sample a point in the chart tangent space within the ball
    """
    def sample(self):
        if self.k == 0:
            return torch.zeros(0, device=self.device, requires_grad=True)
        z = torch.randn(self.k, device=self.device, requires_grad=True)
        r = Chart.rho_s * torch.rand(1, device=self.device).pow(1.0 / self.k)
        u = r * z / z.norm()
        return u
    
    """
    Add a node to this chart
    """
    def add_node(self, node):
        self.nodes.append(node)

    """
    Add a neighbor chart and add a linear inequality associated with it
    """
    def add_neighbor(self, c, is_moving = True):
        uc = self.psi_inv(c.xc)
        l = (uc, 0.5 * torch.dot(uc, uc))
        self.L.append(l)
        self.neighbors.append(c)

        if not is_moving:
            return
        i = 0
        while i < len(self.nodes):
            if torch.dot(self.nodes[i].u, l[0]) >= l[1]:
                node = self.nodes.pop(i)
                c.add_node(node)
                node.move_to(c)
            else:
                i = i + 1

    """
    Count the number of nodes from tree T in this chart
    """
    def get_num_nodes(self, T):
        num = 0
        for node in self.nodes:
            if node.tree is T:
                num = num + 1
        return num
    
    """
    Decide whether this chart has been reached by tree T
    """
    def is_reached_by(self, T):
        for node in self.nodes:
            if node.tree is T:
                return True
        return False

class Atlas:
    """
    The atlas constrcuted for approximating the constraint manifold

    Parameters:
    ----------
    xs: n-dimension torch.tensor
        The starting point in ambient space
    xg: n-dimension torch.tensor
        The goal point in ambient space
    F: function
        The implicit constraint function
    """
    def __init__(self, xs, xg, F):
        self.charts = [Chart(xs, F, 0), Chart(xg, F, 1)]
        self.chart_num = 2
        self.F = F

    """
    Find all neighboring charts near a certain chart
    
    Parameters:
    ----------
    c: Chart
        The chart that is querying neighboring charts

    Returen:
    ----------
    neighbor_chart_indexes: list[int]
        The indexes of all neighboring charts of the new chart
    """
    def _find_neighbor_charts(self, query_chart):
        neighbor_charts = []
        for chart in self.charts:
            if torch.norm(chart.xc - query_chart.xc, p = 2) <= 2 * Chart.rho:
                neighbor_charts.append(chart.index)
        return neighbor_charts

    """
    Add a new chart in the atlas and return the new chart
    """
    def add_chart(self, x):
        new_chart = Chart(x, self.F, self.chart_num)
        neighbor_chart_indexes = self._find_neighbor_charts(new_chart)

        for i in neighbor_chart_indexes:
            neighbor_chart = self.charts[i]
            neighbor_chart.add_neighbor(new_chart)
            new_chart.add_neighbor(neighbor_chart, is_moving=False)

        self.charts.append(new_chart)
        self.chart_num = self.chart_num + 1

        return new_chart

    def get_chart(self, index) -> Chart:
        return self.charts[index]

class AtlasRRTNode:
    """
    A tree node in Atlas-RRT

    Parameters:
    ----------
    node_index: int
        The node's index in its tree's node list
    x: n-dimension torch.tensor
        The point coordinate in ambient space
    c: Chart
        The chart that this node belongs to
    u: k-dimension torch.tensor
        The point coordinate in tangent space
    tree: AtlasRRTree
        The tree that this node belongs to
    parent: AtlasRRTNode
        The parent node of this node in tree
    """
    def __init__(self, node_index, x: torch.tensor, c: Chart, 
                 u = None, tree = None, parent = None):
        self.node_index = node_index                # The node index in tree node list
        self.x = x
        self.chart = c
        if u is None:
            self.u = c.psi_inv(x)
        else:
            self.u = u
        self.tree = tree
        self.parent = parent

        c.add_node(self)                            # Add self to chart c's node list

    """
    Move this node to a new chart
    """
    def move_to(self, c: Chart):
        self.chart = c
        self.u = c.psi_inv(self.x)

class AtlasRRTree:
    delta = 1e-2                                    # Step of branch extension
    lambda_ = 3.0                                   # Branch length regularization

    """
    Tree in Atlas-RRT

    Parameters:
    ----------
    x_root: n-dimension torch.tensor
        The root point coordinate in ambient space
    atlas: Atlas
        The atlas that this tree is referring to
    chart: Chart
        The chart where the root node belongs to
    Collision: function
        The collision check function 
    """
    def __init__(self, x_root: torch.tensor, atlas: Atlas, chart: Chart, Collision):
        self.root = AtlasRRTNode(0, x_root, chart, None, self, None)
        chart.add_node(self.root)                   # Add node to the chart
        self.atlas = atlas                          # The binded atlas for this tree
        self.Collision = Collision                  # Collision check function
        self.nodes = [self.root]                    # All nodes in this tree
        self.node_num = 1                           # Total number of nodes in tree
        self.device = chart.device

    """
    Sample a point in the atlas within all charts that have been reached by this tree
    """
    def sample(self):
        node_charts = torch.tensor([node.chart.index for node in self.nodes],
                                     dtype=torch.long, device=self.device)
        counts = torch.bincount(node_charts)
        nonzero_mask = counts > 0
        weights = torch.zeros_like(counts, dtype=torch.float, device=self.device)
        weights[nonzero_mask] = 1.0 / (counts[nonzero_mask].float() + 1.0)
        probs = weights / weights.sum()
        while True:
            r = torch.multinomial(probs, 1).item()
            chart = self.atlas.get_chart(r)
            ur = chart.sample()
            if chart.in_P(ur):
                break
        return chart, ur
    
    """
    Get the nearest node to a specific point (from neighboring charts if there is any)

    Parameters:
    ----------
    xr: n-dimension torch.tensor
        The random point thet to be extended
    chart: Chart
        The chart where this random point is sampled
    """
    def get_nearest_node(self, xr, chart: Chart = None) -> int:
        nearest_dis = torch.inf
        if chart is not None:                       # Search only ego and neighbor charts
            search_range = chart.nodes
            for neighbor_chart in chart.neighbors:
                search_range = search_range + neighbor_chart.nodes
        else:
            search_range = self.nodes
        
        for node in search_range:
            if not node.tree is self:               # Might meet nodes from other trees
                continue
            dis = torch.norm(node.x - xr)           # Approximate using metric distance
            if dis < nearest_dis:
                nearest_dis = dis
                nearest_node_index = node.node_index
        return nearest_node_index

    """
    Extend from current tree to a given ambient space point and return ending node index

    Parameters:
    ----------
    xr: n-dimension torch.tensor
        The random point thet to be extended
    node_index: int
        The index of the node from where to be extended
    is_explore: bool
        Whether the extension is exploring. If true, xr is not on the manifold

    Returen:
    ----------
    last_node_index: int
        The index of the last extended node (node_index if no extension happened)
    """
    def extend(self, xr, node_index, is_explore) -> int:
        branch = [node_index]                       # List of node indexes in new branch
        x0 = self.nodes[node_index].x               # Start point
        path_length = 0                             # Current path length
        path_len_lb = torch.norm(xr - x0, p = 2)    # Path length lower bound
        chart_created = False                       # Whether a chart has been created
        while True:
            node = self.nodes[branch[-1]]           # The node to be extended
            chart = node.chart                      # The chart where this node is at
            un = node.u
            xn = node.x
            ur = chart.psi_inv(xr)
            if torch.norm(ur - un, p = 2) < AtlasRRTree.delta:
                break                               # STOP: If close enough to target
            uj = un + (ur - un) * AtlasRRTree.delta / torch.norm(ur - un, p = 2)
            xj = chart.psi(uj)
            ds = torch.norm(xj - xn, p = 2)         # Traveled distance on manifold
            if self.Collision(xj):
                break                               # STOP: If collision is detected
            if chart.in_V(uj, xj, ds / AtlasRRTree.delta):
                if not chart.in_P(uj):              # Traveled to a neighboring chart
                    if chart_created:
                        break                       # STOP: Prevent excessive refinement
                    chart = chart.find_best_neighbor(uj, xj)
                    if not is_explore and chart.is_reached_by(self):
                        break                       # STOP: Prevent excessive refinement
            else:                                   # A new chart needs to be created
                self.atlas.add_chart(node.x)
                chart_created = True
                chart = node.chart                  # Now it should have changed
            self.nodes.append(AtlasRRTNode(self.node_num, xj, chart, None, self, node))
            branch.append(self.node_num)
            self.node_num = self.node_num + 1
            chart.add_node(self.nodes[-1])
            path_length = path_length + ds
            if torch.norm(xj - x0, p = 2) > path_len_lb:
                break                               # STOP: Traveled far enough
            if path_length > AtlasRRTree.lambda_ * path_len_lb:
                break                               # STOP: Traveled long enough

        return branch[-1]
    
    """
    Get the path from root to a node, its index is given as the parameter
    """
    def get_path(self, node_index) -> list:
        path = []
        node = self.nodes[node_index]
        while True:
            if node is None:
                break
            path.append(node.x)
            node = node.parent
        path.reverse()
        return path

class AtlasRRTPlanner:
    """
    The motion planner using Atlas-RRT method

    Parameters:
    ----------
    xs: n-dimension torch.tensor
        The starting point in ambient space
    xg: n-dimension torch.tensor
        The goal point in ambient space
    F: function
        The implicit constraint function
    Collision: function
        The collision check function 
    """
    def __init__(self, xs: torch.tensor, xg: torch.tensor, F, Collision):
        self.xs = xs
        self.xg = xg
        self.atlas = Atlas(xs, xg, F)
        self.Ts = AtlasRRTree(xs, self.atlas, self.atlas.get_chart(0), Collision)
        self.Tg = AtlasRRTree(xg, self.atlas, self.atlas.get_chart(1), Collision)

    def plan(self, time_budget = 60.0):
        trees = [self.Ts, self.Tg]
        i = 0
        start_time = time.time()
        while True:
            chart, ur = trees[i].sample()
            xr = chart.phi(ur)
            node_index_0 = trees[i].get_nearest_node(xr, chart)
            ni0 = trees[i].extend(xr, node_index_0, is_explore=True)
            xl0 = trees[i].nodes[ni0].x
            node_index_1 = trees[1 - i].get_nearest_node(xr)
            ni1 = trees[1 - i].extend(xr, node_index_1, is_explore=False)
            xl1 = trees[1 - i].nodes[ni1].x
            if torch.norm(xl0 - xl1, 2) < AtlasRRTree.delta:
                break
            if time.time() - start_time > time_budget:
                print("\033[91mRunning out of time budget!\033[0m")
                return []
            i = 1 - i
        path_1st_half = trees[i].get_path(ni0)
        path_2nd_half = trees[1 - i].get_path(ni1)
        path_2nd_half.reverse()
        path = path_1st_half + path_2nd_half
        if i == 1:
            path.reverse()
        return path
    